steps:
  - name: python:3.11-slim
    entrypoint: bash
    args:
      - "-c"
      - pip install poetry && poetry install && poetry run pytest

  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]
