steps:
  - name: python:3.11-slim
    entrypoint: bash
    args:
      - "-c"
      - pip install poetry && poetry install && poetry run pytest

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "he21-atl-jan-zeugin",
        "--image",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "--min-instances",
        "0",
        "--max-instances",
        "1",
        "--region",
        "europe-west1",
        "--allow-unauthenticated",
        "--port",
        "8000",
      ]
