steps:
  - name: python:3.11-slim
    entrypoint: bash
    args:
      - "-c"
      - pip install poetry && poetry install && poetry run pytest

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/he21_atl_material_lager:$COMMIT_SHA",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/he21_atl_material_lager:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "he21_atl_jan_zeugin",
        "--image",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "--region",
        "europe-west1",
        "--allow-unauthenticated",
      ]
